# Generated by Django 6.1 on 2026-08-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
    ]
